### ISSUE TITLE
MQTT Message format

### ISSUE THREAD

**Issue by kwalkerk** [bonjour81/station_meteo#2]
I have this code running and it receives the messages from the MQTT server.  But I cannot determine how to format the MQTT message so that it is properly decoded.  Could you possibly show a sample message that could be sent using mosquito_pub?  Thanks

**Comment by kwalkerk** [comment]
I think I may have figured it out.  It looks like the driver was designed to receive a single measurement at a time with the appropriate topic and message.

I was trying to send the entire measurement packet from the Davis 6257.  Got it working sending one at a time, think I'll fork the repository and see if I can make it work by sending the whole packet

**Comment by bonjour81** [comment]
I updated readme to clarify
https://github.com/bonjour81/station_meteo/commit/37e03f8aa7d2c58c3dbd08ac8a1e5ef09d0eda9f
