### ISSUE TITLE
wxMesh.py: problem with Python3 , weewx 4.1.1

### ISSUE THREAD

**Issue by peters77** [bonjour81/station_meteo#4]
Hi,

I saw you use the wxMesh.py driver. Sadly I'm not able to fix this: there seems to be some Py3 incompatibility with the wxMesh driver!

I got these error if I install it on Python3 and latest weewx 4.1.1 version:

Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: Caught unrecoverable exception: 
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: **** invalid syntax (wxMesh.py, line 66) 
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: **** Traceback (most recent call last): 
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: **** File "/usr/share/weewx/weewxd", line 148, in main 
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: **** engine = weewx.engine.StdEngine(config_dict) 
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: **** File "/usr/share/weewx/weewx/engine.py", line 69, in __init__ Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: **** self.setupStation(config_dict) 
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: **** File "/usr/share/weewx/weewx/engine.py", line 92, in setupStation Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: **** __import__(driver) 
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: **** File "/usr/share/weewx/user/wxMesh.py", line 66 
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: **** except ValueError, e: 
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: **** ^ 
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: **** SyntaxError: invalid syntax 
Jun 22 14:29:32 weewx weewx[10986] CRITICAL __main__: **** Exiting.

Could you fix this!? 
Would be great...maybe you find some time to look into that?

Regards,

Christian

**Comment by bonjour81** [comment]
Hi ! Sorry for sooo late answer! 
I am currently moving my station on weewx 4.xx and just updated the driver.
This is based on the work from @norecords here:
https://github.com/norecords/weewxMQTT/commit/ebb2905096ec74a8d690d33e87a4d7bb25f90f82
it's barely tested a couple of hours for now.

**Comment by norecords** [comment]
Hi, since my commit  it run without problems. I'm actually on weewx 4.4.1.

**Comment by bonjour81** [comment]
As it runs for a while now with no issue on my station since c4dc89bb6e515be42dc109ae2c56a57634e02360, I close the issue.
