### ISSUE TITLE
MQTT_Barometer - a few modifications for raspberry pi compatibility 

### ISSUE THREAD

**Issue by gdlesage** [bonjour81/station_meteo#5]
Works great on a raspberry pi with a few modifications of the script

mqttuser = "user_name"  #double quotes instead of single quotes
mqttpass = "password"    #double quotes instead of single quotes
bus = smbus.SMBus(1)     #1 instead of 0
mqttc.username_pw_set(mqttuser,mqttpass)  #no quotes around mqttuser or mqttpass

thanks for the great work

**Comment by bonjour81** [comment]
Hi ! thanks for feedback !
I will add your comments in the readme, Raspberry users may be interested.

**Comment by bonjour81** [comment]
Would you mind let me know which version of Raspberry pi so I can add it ?

**Comment by gdlesage** [comment]
I am using raspberry pi 2 
bus = smbus.SMBus(1)  maybe  0 rather than 1 for other raspberry pi versions

raspberry pi users need to turn on ic2 interface by setup command:

sudo raspi-config

thanks for your work
    On Saturday, September 25, 2021, 07:10:46 AM EDT, bonjour81 ***@***.***> wrote:  
 
 


Would you mind let me know which version of Raspberry pi so I can add it ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bonjour81** [comment]
I updated the readme file with the information. Thank you for sharing you RPi experience! it may be useful for some people..and maybe me if some day I change my hardware).

https://github.com/bonjour81/station_meteo/blob/master/sensors/MQTT_Barometer/README.md

If all is fine, I will close the issue.
